# Embed ggml-metal.metal (with merged headers) for LM_GGML_METAL_EMBED_LIBRARY.
# Runtime compiles shaders from the embedded source — no default.metallib bundle needed.

set(METALLIB_COMMON "${SOURCE_DIR}/ggml-common.h")
set(METALLIB_SOURCE "${SOURCE_DIR}/ggml-metal.metal")
set(METALLIB_IMPL "${SOURCE_DIR}/ggml-metal-impl.h")
set(METALLIB_EMBED_SCRIPT "${CMAKE_CURRENT_SOURCE_DIR}/embed-metal-shaders.sh")

file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/autogenerated")

set(METALLIB_EMBED_ASM "${CMAKE_CURRENT_BINARY_DIR}/autogenerated/ggml-metal-embed.s")
set(METALLIB_SOURCE_EMBED "${CMAKE_CURRENT_BINARY_DIR}/autogenerated/ggml-metal-embed.metal")

add_custom_command(
    OUTPUT "${METALLIB_EMBED_ASM}"
    COMMAND "${METALLIB_EMBED_SCRIPT}"
        "${METALLIB_COMMON}"
        "${METALLIB_SOURCE}"
        "${METALLIB_IMPL}"
        "${METALLIB_EMBED_ASM}"
        "${METALLIB_SOURCE_EMBED}"
    DEPENDS
        "${METALLIB_EMBED_SCRIPT}"
        "${METALLIB_COMMON}"
        "${METALLIB_SOURCE}"
        "${METALLIB_IMPL}"
    COMMENT "Generate assembly for embedded Metal shader source"
    VERBATIM
)
