use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Resolve upstream llama.cpp (ggml/llama sources). Prefer `LLAMA_CPP_UPSTREAM`, else
/// `third_party/llama.cpp` next to the crate. Legacy flat `cpp/` is no longer used here.
fn workspace_upstream_dir(crate_dir: &Path) -> PathBuf {
    if let Ok(p) = env::var("LLAMA_CPP_UPSTREAM") {
        let p = PathBuf::from(p);
        if p.exists() {
            return p;
        }
    }
    crate_dir
        .parent()
        .map(|p| p.join("third_party").join("llama.cpp"))
        .unwrap_or_else(|| crate_dir.join("third_party").join("llama.cpp"))
}

fn workspace_native_dir(crate_dir: &Path) -> PathBuf {
    crate_dir
        .parent()
        .map(|p| p.join("native"))
        .unwrap_or_else(|| crate_dir.join("native"))
}

fn push_if_exists(list: &mut Vec<PathBuf>, path: PathBuf, kind: &str) {
    if path.exists() {
        println!("cargo:rerun-if-changed={}", path.display());
        list.push(path);
    } else {
        println!(
            "cargo:warning=Skipping missing {kind} during wasm embed: {}",
            path.display()
        );
    }
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-check-cfg=cfg(llama_embed_cpp)");
    println!("cargo:rustc-check-cfg=cfg(capllama_wasm_jspi)");
    println!("cargo:rustc-check-cfg=cfg(capllama_wasm_pthread)");
    println!("cargo:rerun-if-env-changed=LLAMA_WASM_EMBED_CPP");
    println!("cargo:rerun-if-env-changed=LLAMA_WASM_SYSROOT");
    println!("cargo:rerun-if-env-changed=LLAMA_WASM_JSPI");
    println!("cargo:rerun-if-env-changed=LLAMA_WASM_PTHREAD");
    println!("cargo:rerun-if-env-changed=LLAMA_CPP_UPSTREAM");

    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string()));
    let upstream = workspace_upstream_dir(&crate_dir);
    let native_dir = workspace_native_dir(&crate_dir);
    let target = env::var("TARGET").unwrap_or_default();

    // Embed llama.cpp C/C++ sources for wasm builds (required for shipped PWA artifacts).
    let embed_cpp = env::var("LLAMA_WASM_EMBED_CPP")
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or_else(|_| target.contains("wasm32"));

    if !embed_cpp {
        if target.contains("wasm32") {
            panic!(
                "llama_engine wasm builds require LLAMA_WASM_EMBED_CPP=1 (use npm run build:wasm)"
            );
        }
        return;
    }
    println!("cargo:rustc-cfg=llama_embed_cpp");

    if !upstream.join("CMakeLists.txt").exists() {
        panic!(
            "Upstream llama.cpp not found at {}. Set LLAMA_CPP_UPSTREAM or init submodule \
             third_party/llama.cpp. (Legacy cpp/ is not used for wasm embeds.)\n\
             Optional cmake path: emcmake cmake -B build-wasm -DLLAMA_BUILD_COMMON=ON \
             -DGGML_NATIVE=OFF (see docs/NATIVE_UPSTREAM.md).",
            upstream.display()
        );
    }
    if !native_dir.exists() {
        panic!(
            "native/ adapters not found at {}. Expected project adapters (cap-*.cpp).",
            native_dir.display()
        );
    }

    let ggml_src = upstream.join("ggml").join("src");
    let llama_src = upstream.join("src");
    let common_dir = upstream.join("common");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Minimal build-info stub (normally generated by upstream cmake from build-info.cpp.in).
    let build_info = out_dir.join("build-info.cpp");
    fs::write(
        &build_info,
        r#"#include "build-info.h"
#include <cstdio>
#include <string>
int LLAMA_BUILD_NUMBER = 0;
char const * LLAMA_COMMIT = "wasm-embed";
char const * LLAMA_COMPILER = "emcc";
char const * LLAMA_BUILD_TARGET = "wasm32";
int llama_build_number(void) { return LLAMA_BUILD_NUMBER; }
const char * llama_commit(void) { return LLAMA_COMMIT; }
const char * llama_compiler(void) { return LLAMA_COMPILER; }
const char * llama_build_target(void) { return LLAMA_BUILD_TARGET; }
const char * llama_build_info(void) {
    static std::string s = "b0-wasm-embed";
    return s.c_str();
}
void llama_print_build_info(void) {
    fprintf(stderr, "%s: build = %d (%s)\n", __func__, llama_build_number(), llama_commit());
}
"#,
    )
    .expect("write build-info.cpp stub");

    // ggml core (paths relative to ggml/src)
    let ggml_rels: &[&str] = &[
        "ggml.c",
        "ggml-alloc.c",
        "ggml-backend.cpp",
        "ggml-backend-reg.cpp",
        "ggml-cpu/ggml-cpu.c",
        "ggml-cpu/ggml-cpu.cpp",
        "ggml-cpu/quants.c",
        "ggml-cpu/traits.cpp",
        "ggml-cpu/repack.cpp",
        "ggml-cpu/unary-ops.cpp",
        "ggml-cpu/binary-ops.cpp",
        "ggml-cpu/vec.cpp",
        "ggml-cpu/ops.cpp",
        "ggml-cpu/arch/wasm/quants.c",
        "ggml-opt.cpp",
        "ggml-threading.cpp",
        "ggml-quants.c",
        "gguf.cpp",
    ];

    // llama core (paths relative to src/) — matches upstream src/CMakeLists.txt (minus models glob)
    let llama_rels: &[&str] = &[
        "llama.cpp",
        "llama-adapter.cpp",
        "llama-arch.cpp",
        "llama-batch.cpp",
        "llama-chat.cpp",
        "llama-context.cpp",
        "llama-cparams.cpp",
        "llama-grammar.cpp",
        "llama-graph.cpp",
        "llama-hparams.cpp",
        "llama-impl.cpp",
        "llama-io.cpp",
        "llama-kv-cache.cpp",
        "llama-kv-cache-iswa.cpp",
        "llama-kv-cache-dsa.cpp",
        "llama-kv-cache-dsv4.cpp",
        "llama-memory.cpp",
        "llama-memory-hybrid.cpp",
        "llama-memory-hybrid-iswa.cpp",
        "llama-memory-recurrent.cpp",
        "llama-mmap.cpp",
        "llama-model-loader.cpp",
        "llama-model-saver.cpp",
        "llama-model.cpp",
        "llama-quant.cpp",
        "llama-sampler.cpp",
        "llama-vocab.cpp",
        "unicode-data.cpp",
        "unicode.cpp",
    ];

    // common utils needed by native adapters (chat / sampling / json schema)
    let common_rels: &[&str] = &[
        "common.cpp",
        "chat.cpp",
        "chat-peg-parser.cpp",
        "chat-auto-parser-helpers.cpp",
        "chat-auto-parser-generator.cpp",
        "chat-diff-analyzer.cpp",
        "peg-parser.cpp",
        "sampling.cpp",
        "log.cpp",
        "json-schema-to-grammar.cpp",
        "unicode.cpp",
        "reasoning-budget.cpp",
        "speculative.cpp",
        "jinja/lexer.cpp",
        "jinja/parser.cpp",
        "jinja/runtime.cpp",
        "jinja/value.cpp",
        "jinja/string.cpp",
        "jinja/caps.cpp",
    ];

    // Project wasm adapters under native/
    let native_rels: &[&str] = &[
        "cap-llama.cpp",
        "cap-completion.cpp",
        "cap-embedding.cpp",
        "cap-ios-bridge.cpp",
        "cap-wasm-jspi.cpp",
        "cap-wasm-fs.cpp",
        "cap-wasm-vfs.cpp",
    ];

    let mut c_sources: Vec<PathBuf> = Vec::new();
    let mut cxx_sources: Vec<PathBuf> = Vec::new();

    let mut add = |base: &Path, rel: &str| {
        let path = base.join(rel);
        match path.extension().and_then(|e| e.to_str()) {
            Some("c") => push_if_exists(&mut c_sources, path, "C source"),
            _ => push_if_exists(&mut cxx_sources, path, "C++ source"),
        }
    };

    for rel in ggml_rels {
        add(&ggml_src, rel);
    }
    for rel in llama_rels {
        add(&llama_src, rel);
    }
    // All architecture model implementations (required by llama-model.cpp)
    if let Ok(entries) = fs::read_dir(llama_src.join("models")) {
        let mut models: Vec<PathBuf> = entries
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("cpp"))
            .collect();
        models.sort();
        for path in models {
            push_if_exists(&mut cxx_sources, path, "model source");
        }
    }
    for rel in common_rels {
        add(&common_dir, rel);
    }
    push_if_exists(&mut cxx_sources, build_info, "build-info stub");
    for rel in native_rels {
        add(&native_dir, rel);
    }

    // Enable WASM SIMD128 for significantly faster quantized matrix multiply (#17).
    let is_wasm = target.contains("wasm");
    if is_wasm {
        println!("cargo:rustc-env=WASM_SIMD=1");
        println!("cargo:rustc-cfg=wasm_simd");
    }

    let include_dirs = [
        upstream.join("include"),
        upstream.join("ggml").join("include"),
        ggml_src.clone(),
        ggml_src.join("ggml-cpu"),
        llama_src.clone(),
        common_dir.clone(),
        upstream.join("vendor"),
        upstream.join("tools").join("mtmd"), // headers only; mtmd objs not embedded for wasm
        out_dir.clone(),
        native_dir.clone(),
    ];

    let mut c_build = cc::Build::new();
    c_build
        .cpp(false)
        .flag("-fPIC")
        // Upstream expects GGML_USE_CPU (set by ggml cmake when GGML_CPU=ON).
        .define("GGML_USE_CPU", None)
        .define("CAPLLAMA_BUILD_WASM", None)
        .warnings(false);
    for inc in &include_dirs {
        c_build.include(inc);
    }

    let mut cxx_build = cc::Build::new();
    cxx_build
        .cpp(true)
        .cpp_link_stdlib(None)
        .std("c++17")
        .flag("-fPIC")
        .define("GGML_USE_CPU", None)
        .define("CAPLLAMA_BUILD_WASM", None)
        .warnings(false);
    for inc in &include_dirs {
        cxx_build.include(inc);
    }

    if is_wasm {
        c_build.flag("-msimd128");
        cxx_build.flag("-msimd128");
    }

    let jspi = env::var("LLAMA_WASM_JSPI")
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(false);
    let pthread = env::var("LLAMA_WASM_PTHREAD")
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(false);

    if jspi {
        c_build.define("CAPLLAMA_BUILD_WASM_JSPI", None);
        cxx_build.define("CAPLLAMA_BUILD_WASM_JSPI", None);
        println!("cargo:rustc-cfg=capllama_wasm_jspi");
        println!("cargo:warning=Building embedded llama.cpp with WASM JSPI token streaming");
    }

    if pthread {
        c_build.flag("-pthread");
        cxx_build.flag("-pthread");
        c_build.define("CAPLLAMA_BUILD_WASM_PTHREAD", None);
        cxx_build.define("CAPLLAMA_BUILD_WASM_PTHREAD", None);
        println!("cargo:rustc-cfg=capllama_wasm_pthread");
        println!("cargo:warning=Building embedded llama.cpp with pthread support (compile only; link at Stage 4)");
    }

    if let Ok(sysroot) = env::var("LLAMA_WASM_SYSROOT") {
        let sysroot_path = PathBuf::from(&sysroot);
        let include = sysroot_path.join("include");
        let cxx_include = include.join("c++").join("v1");
        let em_lib = sysroot_path.join("lib").join("wasm32-emscripten");
        let target_is_emscripten = target.contains("emscripten");
        if include.exists() && !target_is_emscripten {
            c_build.flag(&format!("--sysroot={}", sysroot));
            cxx_build.flag(&format!("--sysroot={}", sysroot));
            c_build.include(&include);
            cxx_build.include(&include);
        }
        if cxx_include.exists() && !target_is_emscripten {
            cxx_build.include(&cxx_include);
        }
        if em_lib.exists() && !target_is_emscripten {
            println!("cargo:rustc-link-search=native={}", em_lib.display());
            println!("cargo:rustc-link-lib=static=c-mt");
            println!("cargo:rustc-link-lib=static=dlmalloc-mt");
            println!("cargo:rustc-link-lib=static=c++-mt-noexcept");
            println!("cargo:rustc-link-lib=static=c++abi-mt-noexcept");
            println!("cargo:rustc-link-lib=static=compiler_rt-mt");
        }
        println!(
            "cargo:warning=Using LLAMA_WASM_SYSROOT={} for embedded compilation",
            sysroot
        );
    }

    for src in c_sources {
        c_build.file(src);
    }
    for src in cxx_sources {
        cxx_build.file(src);
    }

    c_build.compile("llama_engine_embedded_c");
    cxx_build.compile("llama_engine_embedded_cpp");

    println!(
        "cargo:warning=Embedded upstream llama.cpp ({} ) + native/ adapters for wasm",
        upstream.display()
    );
}
